In [ ]:
import random
print("Number guessing game")
number=random.randint(1,9)
chance=0        #tracks chances
print("Please guess a number between 1 and 9")
while chance<5:
    guess=int(input("Enter a number : "))
    if guess==number:
        print("Congrats!! You won!")
        break
    elif guess<number:
            print("Guess is low")
    else:
        print("Guess is high")
    chance+=1
if not chance<5:
    print("Number is ", number)
    print("You lost the betting game")

Number guessing game
Please guess a number between 1 and 9
Enter a number : 4
Guess is low
Enter a number : 10
Guess is high
Enter a number : 2
Guess is low
Enter a number : 3
Guess is low
Enter a number : 6
Guess is high
Number is  5
You lost the betting game


In [ ]:
'''Data analysys=> numpy, panda
    numpy=>excel
    panda=>sql
    data analytics=> data and machine learning=> automations
    Eigen vectors=>analytics=>Data cleaning'''

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#np. zeros , ones , linspace

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3))

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
#Identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)

array([0.41887729, 0.37529196])

In [ ]:
np.random.rand(5,5)

array([[0.65341494, 0.26811791, 0.91502319, 0.1304642 , 0.47663965],
       [0.3268131 , 0.74885856, 0.16874698, 0.8364352 , 0.14927154],
       [0.14768138, 0.21895606, 0.96128769, 0.03746183, 0.78121631],
       [0.17786069, 0.31004595, 0.05161875, 0.95620467, 0.47987095],
       [0.11821003, 0.03233094, 0.71526982, 0.03900345, 0.61743653]])

In [ ]:
np.random.randn(5,5)

array([[ 1.01636870e+00,  7.36700763e-01,  2.22522326e-02,
        -8.38542894e-01,  1.46930268e+00],
       [ 1.46041441e-03, -1.16602173e+00,  1.07490502e+00,
         1.12447305e+00,  6.44910497e-01],
       [ 1.13882796e+00,  6.31564002e-01, -1.07823980e+00,
        -2.19246334e+00, -1.08472926e+00],
       [ 1.54598078e+00, -1.25397570e-01,  2.11277859e+00,
        -9.52079807e-03, -1.41706077e+00],
       [ 6.96136611e-01,  6.75797992e-01, -3.25233281e-02,
         7.04285850e-01,  1.05085527e+00]])

In [ ]:
np.random.randint(10)

6

In [ ]:
np.random.randint(1,100,10)

array([67, 88, 11, 61, 62, 15, 48, 33, 81, 99])

In [ ]:
arr=np.arange(25)

In [ ]:
ranarr=np.random.randint(0,50,10)


In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([35,  6,  2, 43, 23,  5,  7, 11, 26,  1])

In [ ]:
arr.reshape(5,5)            #converting arr from 1d to 2d array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

array([35,  6,  2, 43, 23,  5,  7, 11, 26,  1])

In [ ]:
ranarr.max()

43

In [ ]:
ranarr.argmax()

3

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

9

In [ ]:
ranarr.shape

(10,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
#nympy is faster than lists...hence it is used

import numpy as np
arr=np.arange(1,10)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr/arr                 #Not defined in some cases..eg. if 0 is present, then, 0/0=>not defined...will get NaN error

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3          #cube of each element of array

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)         #e^1 e^2 e^3

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [ ]:
np.max(arr)

9

In [ ]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr[7]

8

In [ ]:
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [ ]:
slice_of_arr=arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   6])

In [ ]:
slice_of_arr[:]=99
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9])

In [ ]:
arr_copy=arr.copy()         #copy by reference
arr_copy

array([99, 99, 99, 99, 99, 99,  7,  8,  9])

In [ ]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1][0]

20

In [ ]:
arr_2d[:2][1:]      #everything b4 2nd, everything after 1st gets printed

array([[20, 25, 30]])

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
import numpy as np
arr2d=np.zeros((10,10))
arr_length=arr2d.shape[1]
for i in range(arr_length):
    arr2d[i]=i

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[6,4,2,5]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr=arr>4

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
from numpy import arange
from timeit import Timer

Nelements = 10000
Ntimeits = 10000

x = arange(Nelements)
y = range(Nelements)

t_numpy = Timer("x.sum()", "from __main__ import x")
t_list = Timer("sum(y)", "from __main__ import y")
print("numpy: %.3e" % (t_numpy.timeit(Ntimeits)/Ntimeits,))
print("list:  %.3e" % (t_list.timeit(Ntimeits)/Ntimeits,))

numpy: 1.090e-05
list:  1.758e-04


In [ ]:
#DONE YESTERDAY
from geopy.geocoders import Nominatim
locator = Nominatim(user_agent='myGeocoder')
location = locator.geocode('Nitte')
print('Latitude = {}, Longitude = {}'.format(location.latitude, location.longitude))
print(location.address)

Latitude = 13.1821507, Longitude = 74.9347608
Nitte, Karkala taluk, Udupi district, Karnataka, India
