In [ ]:
!ls

sample_data


In [ ]:
!git clone https://github.com/aniforverizon/nitte_data

Cloning into 'nitte_data'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.


In [ ]:
!ls

nitte_data  sample_data


In [ ]:
!cd nitte_data

In [ ]:
!ls

nitte_data  sample_data


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [ ]:
arr

array([10, 20, 30])

In [ ]:
d

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
arr

array([10, 20, 30])

In [ ]:
pd.Series(labels,my_list)

10    a
20    b
30    c
dtype: object

In [ ]:
arr

array([10, 20, 30])

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
d

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
ser_1=pd.Series([1,2,3,4],index=['USA','INDIA','CHINA','JAPAN'])
ser_2=pd.Series([1,2,3,4],index=['USA','INDIA','Italy','JAPAN'])

In [ ]:
ser_1

USA      1
INDIA    2
CHINA    3
JAPAN    4
dtype: int64

In [ ]:
ser_1['USA']            #USA is linked to 1....output will be 1

1

In [ ]:
ser_1+ser_2             #same values=add, different values= NaN

CHINA    NaN
INDIA    4.0
Italy    NaN
JAPAN    8.0
USA      2.0
dtype: float64

In [ ]:
from numpy.random import randn
np.random.seed(101)

In [ ]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split() ,
                columns='W X Y Z'.split())

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df['Y']

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df.W      #SQL

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
type(df['W'])

pandas.core.series.Series

In [ ]:
df['new']=df['W']+df['Y']

In [ ]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df      #not removing it from the dataframe

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [ ]:
df.loc['B','Y']

-0.8480769834036315

In [ ]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [ ]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [ ]:
df[(df['W']>0)&(df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
newind='CA NY WY OR CO'.split()

In [ ]:
df['States']=newind

In [ ]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [ ]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [ ]:
df=pd.DataFrame({
    'A':[1,2,np.nan],
    'B':[6,np.nan,np.nan],
    'C':[7,8,9]
})

In [ ]:
df

A    B  C
0  1.0  6.0  7
1  2.0  NaN  8
2  NaN  NaN  9

In [ ]:
df.dropna()

A    B  C
0  1.0  6.0  7

In [ ]:
df.dropna(axis=1)

C
0  7
1  8
2  9

In [ ]:
df

A    B  C
0  1.0  6.0  7
1  2.0  NaN  8
2  NaN  NaN  9

In [ ]:
df.fillna(value="Empty")

A      B  C
0      1      6  7
1      2  Empty  8
2  Empty  Empty  9

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64